server:
  port: ${PRODUCT_PORT}
  
spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

  application:
    name: product-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESHOST}:5432/product-db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql

  jpa:
    hibernate:
      format_sql: true
      ddl-auto: create
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

  rabbitmq:
    host: ${RABBIT_MQ_HOST}
    port: ${RABBIT_MQ_PORT}
    username: ${RABBIT_MQ_USER}
    password: ${RABBIT_MQ_PASS}

app-config:

  services:
    sales: http://localhost:${SALES_PORT}

  secrets:
    jwt_secret: ${JWT_SECRET}

  rabbit:
    exchange:
      product: ${PRODUCT_TOPIC}

    routingKey:
      product-stock: ${PRODUCT_STOCK_UPDATE_ROUTING_KEY}
      sales-confirmation: ${SALES_CONFIRMATION_ROUTING_KEY}

    queue:
      product-stock: ${PRODUCT_STOCK_UPDATE_QUEUE}
      sales-confirmation: ${SALES_CONFIRMATION_QUEUE}